"""Run one Folsom year/month calibration and save its parameters.

This script:
- uses the existing preprocessing.FolsomPreprocessor
- keeps the original Folsom source unchanged
- calibrates one year/month at a time
- saves only the monthly calibration parameters as JSON
- does not generate per-image 3D .npy files

Example:
    python scripts/calibrate_month.py --year 2014 --month 1
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from preprocessing.folsom_adapter import FolsomPreprocessor


DEFAULT_IMAGE_ROOT = "/storage2/CV_Irradiance/datasets/1_Folsom"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run Folsom monthly calibration."
    )
    parser.add_argument(
        "--year",
        type=int,
        required=True,
        choices=(2014, 2015, 2016),
        help="Folsom dataset year.",
    )
    parser.add_argument(
        "--month",
        type=int,
        required=True,
        choices=range(1, 13),
        help="Month number (1-12).",
    )
    parser.add_argument(
        "--image-root",
        default=DEFAULT_IMAGE_ROOT,
        help="Root directory of the Folsom image dataset.",
    )
    parser.add_argument(
        "--output-dir",
        default="calibration_results",
        help="Directory where the monthly JSON result is saved.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / (
        f"Folsom_{args.year}_{args.month:02d}_monthly_calibration.json"
    )

    print("=" * 70)
    print("FOLSOM MONTHLY CALIBRATION")
    print("=" * 70)
    print(f"Year       : {args.year}")
    print(f"Month      : {args.month:02d}")
    print(f"Image root : {args.image_root}")
    print(f"Output     : {output_path}")
    print()
    print("The original Folsom source is not modified.")
    print("No per-image 3D .npy files will be generated by this script.")
    print()
    print("Starting calibration...")
    print()

    processor = FolsomPreprocessor(
        year=args.year,
        image_root=args.image_root,
    )

    calibration = processor.calibrate_month(args.month)

    result = {
        "dataset": "Folsom",
        "year": calibration.year,
        "month": calibration.month,
        "cx": calibration.cx,
        "cy": calibration.cy,
        "radius": calibration.radius,
        "projection_model": "theta_deg = 90 * (r_norm ** p)",
        "p": calibration.p,
        "azimuth_model": (
            "predicted_azimuth = "
            "az_sign * (image_phi - az_alpha)"
        ),
        "az_sign": calibration.az_sign,
        "az_alpha_deg": calibration.az_alpha_deg,
        "map_x_shape": list(calibration.map_x.shape),
        "map_y_shape": list(calibration.map_y.shape),
    }

    with output_path.open("w") as file:
        json.dump(result, file, indent=4)

    print()
    print("=" * 70)
    print("CALIBRATION COMPLETED")
    print("=" * 70)
    print(f"P                 : {calibration.p:.6f}")
    print(f"Azimuth sign      : {calibration.az_sign}")
    print(f"Azimuth alpha     : {calibration.az_alpha_deg:.6f} deg")
    print(f"Sky center        : ({calibration.cx:.6f}, {calibration.cy:.6f})")
    print(f"Sky radius        : {calibration.radius:.6f}")
    print(f"Map shape         : {calibration.map_x.shape}")
    print()
    print(f"Saved JSON: {output_path}")


if __name__ == "__main__":
    main()
